### ISSUE TITLE
Not working with @react-native-community/netinfo

### ISSUE THREAD

**Issue by yash-vaghela21** [SabriGhazali/react-native-jitsi-meet-sdk#1]
Not working with the netinfo. already excluded netinfo in the build.gradle

`com.facebook.react.bridge.NativeArgumentsParseException: RNCNetInfo.getCurrentState got 2 arguments, expected 3
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:348)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by SabriGhazali** [comment]
I'm working with react-native-community/netinfo in my project and i'm excluding the library like this : 

`exclude group: 'com.facebook.react',module:'react-native-community_netinfo'`

**Comment by SabriGhazali** [comment]
I'm using react-native-community/netinfo in my project and i'm excluding the library like this :

`exclude group: 'com.facebook.react',module:'react-native-community_netinfo'`

or try to install the `@react-native-community/netinfo@5.0.0` version

**Comment by yash-vaghela21** [comment]
i have already excluded it but it worked after downgrade it netinfo to `5.0.0`
Thank you
